import './jspdf';

import './plugins/acroform';
import './plugins/addhtml';
import './plugins/addimage';
import './plugins/annotations';
import './plugins/arabic';
import './plugins/autoprint';
import './plugins/canvas';
import './plugins/cell';
import './plugins/context2d';
import './plugins/from_html';
import './plugins/javascript';
import './plugins/outline';
import './plugins/png_support';
import './plugins/gif_support';
import './plugins/bmp_support';
import './plugins/setlanguage';
import './plugins/split_text_to_size';
import './plugins/standard_fonts_metrics';
import './plugins/ttfsupport';
import './plugins/svg';
import './plugins/total_pages';
import './plugins/viewerpreferences';
import './plugins/xmp_metadata';
import './plugins/utf8';
import './plugins/vfs';

import './node_modules/cf-blob.js/Blob.js';
import './node_modules/file-saver/FileSaver.js';
import './libs/adler32cs.js';
import './node_modules/omggif/omggif.js';
import './libs/JPEGEncoder.js';
import './libs/BMPDecoder.js';
import './libs/Deflater.js';
import './libs/rgbcolor.js';
import './libs/html2canvas/dist/html2canvas.js';
import './libs/ttffont.js';
import './libs/png_support/png.js';
import './libs/png_support/zlib.js';
import './libs/polyfill.js';

export default jsPDF;
