import { Component } from '@angular/core';
import { jsPDF} from "jspdf"

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  
  text:string="This is generated by jsPDF"
  pdfSrc : string;
  generatePDF(){

    //Initialize the Document
    let doc = new jsPDF();
    doc.text(this.text,10,10)

    //Convert Document to a Blob
    var blobPDF =  new Blob([ doc.output() ], { type : 'application/pdf'});
    // Create Blob URL
    let url = window.URL.createObjectURL(blobPDF)
    // Use blob URL to display PDF in PDFViewer
    this.pdfSrc = url

    //To save the PDF uncomment below line
    // doc.save("jsPDF.pdf")
  }

}
