import { Component } from '@angular/core';
import { jsPDF } from "jspdf"

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  text: string = "This is generated by jsPDF"
  pdfSrc: string;

  textExample: boolean = false;
  htmlExample: boolean = true;
  canvgExample: boolean = false;

  viewTextToPDF() {
    this.textExample = true
    this.htmlExample = false
    this.canvgExample = false
  }

  viewHTMLToPDF() {
    this.textExample = false
    this.htmlExample = true
    this.canvgExample = false
  }

  viewCanvgToPDF() {
    this.textExample = false
    this.htmlExample = false
    this.canvgExample = true
  }

  generatePDFFromText() {

    //Initialize the Document
    let doc = new jsPDF();
    doc.text(this.text, 10, 10)

    //Convert Document to a Blob
    var blobPDF = doc.output('blob')
    // Create Blob URL
    let url = window.URL.createObjectURL(blobPDF)
    // Use blob URL to display PDF in PDFViewer
    this.pdfSrc = url

    //To save the PDF uncomment below line
    // doc.save("jsPDF.pdf")
  }
  
  
  async generatePDFFromHTML() {
    var pdf = new jsPDF('p', 'pt', 'letter');
    
    pdf.html(document.getElementById("iFrame")).then((doc) => {
      
      //Convert Document to a Blob
      var blobPDF = pdf.output('blob')
      // Create Blob URL
      let url = window.URL.createObjectURL(blobPDF)
      // Use blob URL to display PDF in PDFViewer
      this.pdfSrc = url
      
    })

  }

}
