name: Continuous Integration

on: [pull_request_target]

jobs:
  test-saucelabs:
    name: Browser tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: npm install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test-saucelabs
        env:
          SAUCE_USERNAME: jspdf
          SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20 # current LTS
          - 22 # latest
    name: Node.js ${{ matrix.node-version }} test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: npm install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test-node

  test-typings:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ts-version:
          - { ts: '4.0', types-node: '17' }
          - { ts: 'latest', types-node: '20' }
    name: Typings tests (typescript@${{ matrix.ts-version.ts }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: npm install
        run: npm ci
      - name: Install typescript@${{ matrix.ts-version.ts }}
        run: npm install typescript@${{ matrix.ts-version.ts }}
      - name: Install @types/node@${{ matrix.ts-version.types-node }}
        run: npm install @types/node@${{ matrix.ts-version.types-node }}
      - name: Run tests
        run: npm run test-typings

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: npm install
        run: npm ci
      - name: Check Prettier
        run: npm run lint
